import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Theme configurations matching frontend presets
const themes = [
  {
    name: 'Classic News',
    slug: 'classic-news',
    description: 'Traditional newspaper layout with serif fonts and professional design',
    version: '1.0.0',
    author: 'JM News',
    isPremium: false,
    previewUrl: '/themes/previews/classic-news.jpg',
    isActive: true,
    cssContent: JSON.stringify({
      colors: {
        primary: '#d97706',
        primaryHover: '#b45309',
        primaryLight: '#fbbf24',
        primaryDark: '#92400e',
        secondary: '#1f2937',
        secondaryHover: '#111827',
        secondaryLight: '#374151',
        secondaryDark: '#0f172a',
        accent: '#3b82f6',
        accentHover: '#2563eb',
        background: '#ffffff',
        backgroundAlt: '#f9fafb',
        backgroundDark: '#111827',
        text: '#111827',
        textMuted: '#6b7280',
        textLight: '#9ca3af',
        textInverse: '#ffffff',
        border: '#e5e7eb',
        borderLight: '#f3f4f6',
        borderDark: '#d1d5db',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      typography: {
        fontHeading: "'Playfair Display', serif",
        fontBody: "'Inter', sans-serif",
        fontMono: "'Fira Code', monospace",
        fontSize: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem', '3xl': '1.875rem', '4xl': '2.25rem', '5xl': '3rem', '6xl': '3.75rem' },
        fontWeight: { light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
        lineHeight: { tight: 1.25, normal: 1.5, relaxed: 1.75, loose: 2 },
        letterSpacing: { tight: '-0.025em', normal: '0', wide: '0.025em', wider: '0.05em' },
      },
      layout: {
        containerWidth: '1280px',
        containerWidthNarrow: '768px',
        containerWidthWide: '1536px',
        sidebarWidth: '320px',
        sidebarPosition: 'right',
        gridColumns: 3,
        gridGap: '1.5rem',
        spacing: 8,
        borderRadius: { none: '0', sm: '0.25rem', base: '0.5rem', lg: '0.75rem', xl: '1rem', full: '9999px' },
        shadow: { sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)', base: '0 1px 3px 0 rgba(0, 0, 0, 0.1)', lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)', xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)' },
      },
      components: {
        header: { style: 'classic', logoPosition: 'center', logoSize: 'lg', navigationStyle: 'horizontal', navigationPosition: 'bottom', showSearch: true, showSocial: true, showDarkModeToggle: true, sticky: true, transparent: false },
        articleCard: { style: 'grid', showExcerpt: true, showAuthor: true, showDate: true, showCategory: true, showReadTime: true, showTags: false, imageAspectRatio: '16/9', imagePosition: 'top', hoverEffect: 'lift' },
        footer: { style: 'multi-column', showNewsletter: true, showSocial: true, showQuickLinks: true, showLegal: true, showCopyright: true, columns: 4 },
        sidebar: { position: 'right', width: '320px', sticky: true, showSearch: true, showCategories: true, showTrending: true, showTags: true, showAds: true, showNewsletter: true },
        articlePage: { layout: 'narrow', readingWidth: '768px', fontSize: '1.125rem', lineHeight: 1.75, showTableOfContents: true, showShareButtons: true, showAuthorBio: true, showRelatedArticles: true, showComments: true },
        comments: { style: 'threaded', maxDepth: 3, showVoting: true, showAvatars: true, allowAnonymous: false, requireModeration: true },
      },
      cssContent: '.article-card { transition: transform 0.2s ease-in-out; border: 1px solid var(--color-border); } .article-card:hover { transform: translateY(-4px); box-shadow: var(--shadow-lg); }',
    }),
  },
  {
    name: 'Minimal Blog',
    slug: 'minimal-blog',
    description: 'Clean brutalist design with monochrome palette and center-aligned layout',
    version: '1.0.0',
    author: 'JM News',
    isPremium: false,
    previewUrl: '/themes/previews/minimal-blog.jpg',
    isActive: false,
    cssContent: JSON.stringify({
      colors: {
        primary: '#000000',
        primaryHover: '#1a1a1a',
        primaryLight: '#333333',
        primaryDark: '#000000',
        secondary: '#ffffff',
        secondaryHover: '#f5f5f5',
        secondaryLight: '#ffffff',
        secondaryDark: '#e5e5e5',
        accent: '#ff0000',
        accentHover: '#cc0000',
        background: '#ffffff',
        backgroundAlt: '#fafafa',
        backgroundDark: '#000000',
        text: '#000000',
        textMuted: '#666666',
        textLight: '#999999',
        textInverse: '#ffffff',
        border: '#e0e0e0',
        borderLight: '#f0f0f0',
        borderDark: '#cccccc',
        success: '#00aa00',
        warning: '#ff9900',
        error: '#ff0000',
        info: '#0066cc',
      },
      typography: {
        fontHeading: "'Inter', sans-serif",
        fontBody: "'Inter', sans-serif",
        fontMono: "'Courier New', monospace",
        fontSize: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem', '3xl': '1.875rem', '4xl': '2.25rem', '5xl': '3rem', '6xl': '3.75rem' },
        fontWeight: { light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
        lineHeight: { tight: 1.25, normal: 1.5, relaxed: 1.75, loose: 2 },
        letterSpacing: { tight: '-0.025em', normal: '0', wide: '0.025em', wider: '0.05em' },
      },
      layout: {
        containerWidth: '800px',
        containerWidthNarrow: '600px',
        containerWidthWide: '1000px',
        sidebarWidth: '0px',
        sidebarPosition: 'none',
        gridColumns: 1,
        gridGap: '2rem',
        spacing: 8,
        borderRadius: { none: '0', sm: '0', base: '0', lg: '0', xl: '0', full: '0' },
        shadow: { sm: 'none', base: 'none', lg: 'none', xl: 'none' },
      },
      components: {
        header: { style: 'minimal', logoPosition: 'center', logoSize: 'md', navigationStyle: 'horizontal', navigationPosition: 'bottom', showSearch: false, showSocial: false, showDarkModeToggle: true, sticky: false, transparent: false },
        articleCard: { style: 'list', showExcerpt: true, showAuthor: false, showDate: true, showCategory: false, showReadTime: true, showTags: false, imageAspectRatio: '16/9', imagePosition: 'top', hoverEffect: 'none' },
        footer: { style: 'minimal', showNewsletter: false, showSocial: true, showQuickLinks: false, showLegal: true, showCopyright: true, columns: 1 },
        sidebar: { position: 'none', width: '0px', sticky: false, showSearch: false, showCategories: false, showTrending: false, showTags: false, showAds: false, showNewsletter: false },
        articlePage: { layout: 'narrow', readingWidth: '600px', fontSize: '1.125rem', lineHeight: 1.75, showTableOfContents: false, showShareButtons: false, showAuthorBio: false, showRelatedArticles: true, showComments: false },
        comments: { style: 'flat', maxDepth: 1, showVoting: false, showAvatars: false, allowAnonymous: true, requireModeration: false },
      },
      cssContent: '.article-card { border-bottom: 2px solid #000; padding: 2rem 0; } .article-card:hover { background: #fafafa; }',
    }),
  },
  {
    name: 'Editorial Magazine',
    slug: 'editorial-magazine',
    description: 'Bold magazine-style layout with striking typography and vibrant colors',
    version: '1.0.0',
    author: 'JM News',
    isPremium: false,
    previewUrl: '/themes/previews/editorial-magazine.jpg',
    isActive: false,
    cssContent: JSON.stringify({
      colors: {
        primary: '#dc2626',
        primaryHover: '#b91c1c',
        primaryLight: '#ef4444',
        primaryDark: '#991b1b',
        secondary: '#1e3a8a',
        secondaryHover: '#1e40af',
        secondaryLight: '#3b82f6',
        secondaryDark: '#1e293b',
        accent: '#f59e0b',
        accentHover: '#d97706',
        background: '#ffffff',
        backgroundAlt: '#f8fafc',
        backgroundDark: '#0f172a',
        text: '#0f172a',
        textMuted: '#64748b',
        textLight: '#94a3b8',
        textInverse: '#ffffff',
        border: '#e2e8f0',
        borderLight: '#f1f5f9',
        borderDark: '#cbd5e1',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#dc2626',
        info: '#3b82f6',
      },
      typography: {
        fontHeading: "'Bebas Neue', sans-serif",
        fontBody: "'Source Sans Pro', sans-serif",
        fontMono: "'Courier New', monospace",
        fontSize: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem', '3xl': '2rem', '4xl': '2.5rem', '5xl': '3.5rem', '6xl': '4.5rem' },
        fontWeight: { light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 900 },
        lineHeight: { tight: 1.1, normal: 1.5, relaxed: 1.75, loose: 2 },
        letterSpacing: { tight: '-0.05em', normal: '0', wide: '0.05em', wider: '0.1em' },
      },
      layout: {
        containerWidth: '1400px',
        containerWidthNarrow: '900px',
        containerWidthWide: '1600px',
        sidebarWidth: '350px',
        sidebarPosition: 'right',
        gridColumns: 4,
        gridGap: '2rem',
        spacing: 12,
        borderRadius: { none: '0', sm: '0.125rem', base: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
        shadow: { sm: '0 2px 4px rgba(0,0,0,0.1)', base: '0 4px 8px rgba(0,0,0,0.15)', lg: '0 8px 16px rgba(0,0,0,0.2)', xl: '0 16px 32px rgba(0,0,0,0.25)' },
      },
      components: {
        header: { style: 'modern', logoPosition: 'left', logoSize: 'lg', navigationStyle: 'horizontal', navigationPosition: 'top', showSearch: true, showSocial: true, showDarkModeToggle: true, sticky: true, transparent: false },
        articleCard: { style: 'featured', showExcerpt: true, showAuthor: true, showDate: true, showCategory: true, showReadTime: true, showTags: true, imageAspectRatio: '21/9', imagePosition: 'background', hoverEffect: 'zoom' },
        footer: { style: 'multi-column', showNewsletter: true, showSocial: true, showQuickLinks: true, showLegal: true, showCopyright: true, columns: 4 },
        sidebar: { position: 'right', width: '350px', sticky: true, showSearch: true, showCategories: true, showTrending: true, showTags: true, showAds: true, showNewsletter: true },
        articlePage: { layout: 'wide', readingWidth: '900px', fontSize: '1.125rem', lineHeight: 1.75, showTableOfContents: true, showShareButtons: true, showAuthorBio: true, showRelatedArticles: true, showComments: true },
        comments: { style: 'threaded', maxDepth: 3, showVoting: true, showAvatars: true, allowAnonymous: false, requireModeration: true },
      },
      cssContent: '.article-card { overflow: hidden; } .article-card img { transition: transform 0.3s; } .article-card:hover img { transform: scale(1.1); }',
    }),
  },
  {
    name: 'Bold Dark',
    slug: 'bold-dark',
    description: 'Cyberpunk-inspired dark theme with neon accents and glassmorphism',
    version: '1.0.0',
    author: 'JM News',
    isPremium: true,
    previewUrl: '/themes/previews/bold-dark.jpg',
    isActive: false,
    cssContent: JSON.stringify({
      colors: {
        primary: '#00ff88',
        primaryHover: '#00cc6f',
        primaryLight: '#33ffaa',
        primaryDark: '#00aa5c',
        secondary: '#8b5cf6',
        secondaryHover: '#7c3aed',
        secondaryLight: '#a78bfa',
        secondaryDark: '#6d28d9',
        accent: '#06b6d4',
        accentHover: '#0891b2',
        background: '#0a0a0a',
        backgroundAlt: '#141414',
        backgroundDark: '#000000',
        text: '#ffffff',
        textMuted: '#a0a0a0',
        textLight: '#d0d0d0',
        textInverse: '#000000',
        border: '#2a2a2a',
        borderLight: '#1a1a1a',
        borderDark: '#3a3a3a',
        success: '#00ff88',
        warning: '#fbbf24',
        error: '#ff0055',
        info: '#06b6d4',
      },
      typography: {
        fontHeading: "'Orbitron', sans-serif",
        fontBody: "'DM Sans', sans-serif",
        fontMono: "'Fira Code', monospace",
        fontSize: { xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem', '2xl': '1.5rem', '3xl': '1.875rem', '4xl': '2.25rem', '5xl': '3rem', '6xl': '4rem' },
        fontWeight: { light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 900 },
        lineHeight: { tight: 1.2, normal: 1.5, relaxed: 1.75, loose: 2 },
        letterSpacing: { tight: '-0.025em', normal: '0', wide: '0.05em', wider: '0.1em' },
      },
      layout: {
        containerWidth: '1280px',
        containerWidthNarrow: '768px',
        containerWidthWide: '1536px',
        sidebarWidth: '320px',
        sidebarPosition: 'right',
        gridColumns: 3,
        gridGap: '1.5rem',
        spacing: 8,
        borderRadius: { none: '0', sm: '0.5rem', base: '0.75rem', lg: '1rem', xl: '1.5rem', full: '9999px' },
        shadow: { sm: '0 0 10px rgba(0,255,136,0.2)', base: '0 0 20px rgba(0,255,136,0.3)', lg: '0 0 30px rgba(0,255,136,0.4)', xl: '0 0 40px rgba(0,255,136,0.5)' },
      },
      components: {
        header: { style: 'modern', logoPosition: 'left', logoSize: 'lg', navigationStyle: 'horizontal', navigationPosition: 'top', showSearch: true, showSocial: true, showDarkModeToggle: false, sticky: true, transparent: true, backgroundColor: 'rgba(10,10,10,0.8)' },
        articleCard: { style: 'grid', showExcerpt: true, showAuthor: true, showDate: true, showCategory: true, showReadTime: true, showTags: true, imageAspectRatio: '16/9', imagePosition: 'top', hoverEffect: 'lift' },
        footer: { style: 'multi-column', showNewsletter: true, showSocial: true, showQuickLinks: true, showLegal: true, showCopyright: true, columns: 4, backgroundColor: 'rgba(20,20,20,0.9)' },
        sidebar: { position: 'right', width: '320px', sticky: true, showSearch: true, showCategories: true, showTrending: true, showTags: true, showAds: true, showNewsletter: true },
        articlePage: { layout: 'narrow', readingWidth: '768px', fontSize: '1.125rem', lineHeight: 1.75, showTableOfContents: true, showShareButtons: true, showAuthorBio: true, showRelatedArticles: true, showComments: true },
        comments: { style: 'threaded', maxDepth: 3, showVoting: true, showAvatars: true, allowAnonymous: false, requireModeration: true },
      },
      cssContent: '.article-card { background: rgba(20,20,20,0.6); backdrop-filter: blur(10px); border: 1px solid rgba(0,255,136,0.2); } .article-card:hover { border-color: #00ff88; box-shadow: 0 0 20px rgba(0,255,136,0.3); }',
    }),
  },
  {
    name: 'Luxury Editorial',
    slug: 'luxury-editorial',
    description: 'High-fashion magazine aesthetic with elegant serif typography and gold accents',
    version: '1.0.0',
    author: 'JM News',
    isPremium: true,
    previewUrl: '/themes/previews/luxury-editorial.jpg',
    isActive: false,
    cssContent: JSON.stringify({
      colors: {
        primary: '#d4af37',
        primaryHover: '#b8941f',
        primaryLight: '#e6c966',
        primaryDark: '#9d7e1a',
        secondary: '#2c2c2c',
        secondaryHover: '#1a1a1a',
        secondaryLight: '#3d3d3d',
        secondaryDark: '#0d0d0d',
        accent: '#8b4513',
        accentHover: '#6b3410',
        background: '#faf8f3',
        backgroundAlt: '#f5f2ea',
        backgroundDark: '#1a1a1a',
        text: '#1a1a1a',
        textMuted: '#6b6b6b',
        textLight: '#9b9b9b',
        textInverse: '#faf8f3',
        border: '#e8e4d9',
        borderLight: '#f0ede3',
        borderDark: '#d4cfc0',
        success: '#2d5016',
        warning: '#d4af37',
        error: '#8b0000',
        info: '#2c5282',
      },
      typography: {
        fontHeading: "'Cormorant Garamond', serif",
        fontBody: "'Crimson Pro', serif",
        fontMono: "'Courier Prime', monospace",
        fontSize: { xs: '0.75rem', sm: '0.875rem', base: '1.0625rem', lg: '1.1875rem', xl: '1.375rem', '2xl': '1.75rem', '3xl': '2.25rem', '4xl': '3rem', '5xl': '4rem', '6xl': '5rem' },
        fontWeight: { light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
        lineHeight: { tight: 1.3, normal: 1.6, relaxed: 1.8, loose: 2.2 },
        letterSpacing: { tight: '-0.025em', normal: '0', wide: '0.025em', wider: '0.075em' },
      },
      layout: {
        containerWidth: '1200px',
        containerWidthNarrow: '700px',
        containerWidthWide: '1400px',
        sidebarWidth: '300px',
        sidebarPosition: 'right',
        gridColumns: 3,
        gridGap: '2.5rem',
        spacing: 12,
        borderRadius: { none: '0', sm: '0.125rem', base: '0.25rem', lg: '0.375rem', xl: '0.5rem', full: '9999px' },
        shadow: { sm: '0 1px 3px rgba(0,0,0,0.08)', base: '0 2px 6px rgba(0,0,0,0.12)', lg: '0 4px 12px rgba(0,0,0,0.15)', xl: '0 8px 24px rgba(0,0,0,0.18)' },
      },
      components: {
        header: { style: 'centered', logoPosition: 'center', logoSize: 'lg', navigationStyle: 'horizontal', navigationPosition: 'bottom', showSearch: true, showSocial: true, showDarkModeToggle: true, sticky: true, transparent: false },
        articleCard: { style: 'masonry', showExcerpt: true, showAuthor: true, showDate: true, showCategory: true, showReadTime: false, showTags: false, imageAspectRatio: '4/3', imagePosition: 'top', hoverEffect: 'fade' },
        footer: { style: 'centered', showNewsletter: true, showSocial: true, showQuickLinks: true, showLegal: true, showCopyright: true, columns: 3 },
        sidebar: { position: 'right', width: '300px', sticky: true, showSearch: false, showCategories: true, showTrending: true, showTags: false, showAds: true, showNewsletter: true },
        articlePage: { layout: 'narrow', readingWidth: '700px', fontSize: '1.1875rem', lineHeight: 1.8, showTableOfContents: false, showShareButtons: true, showAuthorBio: true, showRelatedArticles: true, showComments: true },
        comments: { style: 'threaded', maxDepth: 2, showVoting: false, showAvatars: true, allowAnonymous: false, requireModeration: true },
      },
      cssContent: '.article-card { border: 1px solid #e8e4d9; background: linear-gradient(to bottom, #faf8f3, #f5f2ea); } .article-card:hover { border-color: #d4af37; }',
    }),
  },
];

async function seedThemes() {
  console.log('🎨 Seeding premium themes...\n');

  for (const themeData of themes) {
    try {
      const theme = await prisma.theme.upsert({
        where: { slug: themeData.slug },
        update: {
          name: themeData.name,
          description: themeData.description,
          version: themeData.version,
          author: themeData.author,
          isPremium: themeData.isPremium,
          previewUrl: themeData.previewUrl,
          cssContent: themeData.cssContent,
        },
        create: themeData,
      });
      
      console.log(`✓ ${theme.name} (${theme.isPremium ? 'Premium' : 'Free'}) - ${theme.isActive ? 'Active' : 'Inactive'}`);
    } catch (error) {
      console.error(`✗ Failed to seed ${themeData.name}:`, error);
    }
  }

  console.log('\n✓ Theme seeding complete!');
}

seedThemes()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
